### ISSUE TITLE
you don't list what it sets up?

### ISSUE THREAD

**Issue by michaelsearcy** [johndavidmartinez/CodeLoubuntu#1]
You should do that. I am not running Ubuntu (though maybe I should on this 2 year old laptop I have from old job)

**Comment by johndavidmartinez** [comment]
Thanks for the feedback. I have added your suggestion. See the commit [here](https://github.com/johndavidmartinez/CodeLoubuntu/commit/617ad00c4b6b4d8d8ea5bb7c71b03cf2dfcfd8ca).
